yaml
name: C Build with Make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Make
        run: make

      - name: Run the program (optional test)
        run: ./calculator

      - name: Clean build files
        run: make clean
